### ISSUE TITLE
Make a live demo

### ISSUE THREAD

**Issue by L1lith** [wpernath/quarkus-grumpycat#15]
It would be fun to be able to just click a link and start playing

**Comment by wpernath** [comment]
Yes, that's true. Perhaps I am able to get access to a Kubernetes / OpenShift cluster. Then I'll definitely deploy a demo instance. Stay tuned!

**Comment by L1lith** [comment]
> Yes, that's true. Perhaps I am able to get access to a Kubernetes / OpenShift cluster. Then I'll definitely deploy a demo instance. Stay tuned!

Would you be able to deploy statically to GitHub pages? Whatever you choose I look forward to seeing it!

**Comment by wpernath** [comment]
Unfortunately not, as it requires some other components to run (it is first of all a deployment example of doing GitOps with a more complex app than 'hello world').
- cat-server (a java backend)
- PostgreSQL database to store highscores etc.
- Apache Kafka to make sure, all enemy movements will be stored in a deferred way

**Comment by wpernath** [comment]
@L1lith , Finally I have a server to install a live demo. Not sure how stable it'll be, but for now you can have a look at it here:

http://cat-client-quarkus-grumpycat.apps.cat.rhepds.com/

Let me know, what you think. And I am always happy for ideas, contributions etc.

Thanks a lot!

**Comment by L1lith** [comment]
> @L1lith , Finally I have a server to install a live demo. Not sure how stable it'll be, but for now you can have a look at it here:
> 
> http://cat-client-quarkus-grumpycat.apps.cat.rhepds.com/
> 
> Let me know, what you think. And I am always happy for ideas, contributions etc.
> 
> Thanks a lot!

Great work! I played it earlier today it was fun :) Thanks for implementing this!

**Comment by wpernath** [comment]
Thank you for the suggestion :-)
