### ISSUE TITLE
The HUD is updating / being drawn every frame... 

### ISSUE THREAD

**Issue by wpernath** [wpernath/quarkus-grumpycat#22]
This costs quite a lot of power. Try to use melonJS drawing as much as possible.

**Comment by L1lith** [comment]
> This costs quite a lot of power. Try to use melonJS drawing as much as possible.

You might be better off switching the HUD to HTML. Just an idea. I love melon but HTML has nice benefits when it comes to performance and accessibility

**Comment by wpernath** [comment]
Thanks! I am testing the new version of the hud right now.

**Comment by wpernath** [comment]
Closing this, because it looks good now.
