### ISSUE TITLE
Remove com.github.javafaker and use net.datafaker instead

### ISSUE THREAD

**Issue by wpernath** [wpernath/quarkus-grumpycat#36]
JavaFaker is too old and clashes with io.quarkus.kubernetes extension. There is a better and more recent implementation available called net.datafaker. Use this implementation instead.

**Comment by bodiam** [comment]
Hi @wpernath , thanks for trying Datafaker. I see you're still using `Faker.instance()`, and we're planning on removing that method, there's really no benefit of using it over `new Faker()`

I've created a PR for it here: https://github.com/wpernath/quarkus-grumpycat/pull/38

**Comment by wpernath** [comment]
Thank you very much!
